all:

u:
	 gcc  -g suma.s -o suma -no-pie -nostartfiles
	./suma

s:
	gcc -g sumasign.s -o sumasign -no-pie -nostartfiles
	./sumasign

m:
	gcc -g media.s -o media -no-pie -nostartfiles
	./media

v:
	gcc -g s32to64.s -o s32to64 -no-pie -nostartfiles
	./s32to64

v2:
	gcc -g 64to128.s -o 64to128 -no-pie -nostartfiles
	./64to128


